### ISSUE TITLE
Versioning FHIR resources

### ISSUE THREAD

**Issue by citizenrich** [jembi/hearth#111]
I'm curious how Hearth can/could handle different versions of the same documents. For a use case, say, for example, that a ministry of health using Hearth has to store different versions of it's facility info because they are updating records and may need to rollback.

I don't see in FHIR how it supports namespaces/domains or other ways to declare something akin to MongoDB collections that are versioned. Interested in your thoughts.

**Comment by rcrichton** [comment]
FHIR does specify that every document is versioned when it is updated. This way you can refer back to an exact version of a document at a particular point in time using the history interaction - See https://www.hl7.org/fhir/http.html#history

Hearth has full history support for all resources. Is this helpful or were you thinking of something different?

**Comment by BMartinos** [comment]
I wonder if the question is more in terms of versioning a set of records instead of the individual record. So for example the ministry of health has loaded 500 facilities as their first starting, this will be considered version 1 of facilities, which can get small updates, like their name etc, but sometime in the future a new list is drafted with say 1500 facilities which will become version 2. Some systems could then still be using version 1 and others version 2 of the list.

I suppose something like this could be done with a coded value where the system specifies the version it is in? but not sure if this is a correct way of doing something like this or even correct in general

**Comment by citizenrich** [comment]
Sorry, I was unclear and mixed up the use cases. So, one use case is versioning as noted where you can use history. Another use case is where you have whole collections of docs that are the same resource type but versioned, like @BMartinos notes. So, in that case, perhaps metadata tags could be useful. Are those supported. See https://thefhirplace.com/2015/03/17/metadata-in-fhir/ on tags.

**Comment by citizenrich** [comment]
Closing as stale.
